---
- name: Kali Setup
  hosts: localhost
  become: yes
  tasks:

     - name: Set Hostname
       ansible.builtin.hostname:
          name: "kali"

     - name: Update apt repo and cache
       apt: 
          update_cache: yes
          cache_valid_time: 3600

     - name: Upgrade all apt packages this can take a long time
       apt: 
            name: "*"
            state: latest
            
     - name: Check Ansible-Dependencies
       apt: 
            name: 
                - python2
                - python3
                - python3-pip
                - wget
                - golang-go
                - trufflehog
                - gpg
                - apt-transport-https
                - pipx
                - rustc
                - python2-dev
                - build-essential
                - yara
                - gobuster
                - seclists
                - kali-desktop-i3
     
     - name: Install Python libraries
       pip: 
            name: 
                - ansible
     - name: Change keyboard layout to de
       ansible.builtin.shell: setxkbmap -layout de
                
     - name: Download python2-pip
       ansible.builtin.get_url:
         url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
         dest: /tmp/get-pip.py

     - name: Install python2-pip
       ansible.builtin.shell: python2 /tmp/get-pip.py

     - name: Install Python2 setuptools
       ansible.builtin.shell: python2 -m pip install setuptools

     - name: Install Python2 Dependencies
       ansible.builtin.shell: python2 -m pip install pycrypto distorm3
     
     - name: Install VSCode x86
       ansible.builtin.apt:
         deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
       when: ansible_facts.architecture == "x86_64"

     - name: Install VSCode ARM
       ansible.builtin.apt:
         deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64
       when: ansible_facts.architecture != "x86_64"

     - name: Git Pull impacket
       git:
         repo: https://github.com/fortra/impacket
         dest: /opt/tools/impacket

     - name: Git Pull ponyshell
       git:
         repo: https://github.com/flozz/p0wny-shell
         dest: /opt/tools/p0wny-shell

     - name: Git Pull powercat
       git:
         repo: https://github.com/besimorhino/powercat
         dest: /opt/tools/powercat

     - name: Install ensurepath
       ansible.builtin.command: 'pipx ensurepath'
       
     - name: Install netexec
       ansible.builtin.command: 'pipx install git+https://github.com/Pennyw0rth/NetExec'

     - name: Creates directory
       ansible.builtin.file:
         path: /opt/tools/peas
         state: directory

     - name: Download linpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh
         dest: /opt/tools/peas/

     - name: Download winpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEASany_ofs.exe
         dest: /opt/tools/peas/winpeas.exe

     - name: Download Kerbrute
       ansible.builtin.get_url:
         url: https://github.com/ropnop/kerbrute/releases/latest/download/kerbrute_linux_amd64
         dest: /opt/tools/

     - name: Download volatitilty2
       git:
         repo: https://github.com/volatilityfoundation/volatility
         dest: /opt/tools/volatility

     - name: Download volatitilty3
       git:
         repo: https://github.com/volatilityfoundation/volatility3
         dest: /opt/tools/volatility3

     - name: Download volatility plugins
       git:
         repo: https://github.com/superponible/volatility-plugins
         dest: /opt/tools/volatility-plugins

     - name: Create Resocks-Folder
       ansible.builtin.file:
         path: /opt/tools/resocks
         state: directory

     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Linux_x86_64.tar.gz
         dest: /opt/tools/resocks/
       when: ansible_facts.architecture == "x86_64"

     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/download/v0.1.1/resocks_Linux_arm64.tar.gz
         dest: /opt/tools/resocks/
       when: ansible_facts.architecture != "x86_64"
         
     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Windows_x86_64.zip
         dest: /opt/tools/resocks/
         
     - name: Download phpreverseshell
       ansible.builtin.get_url:
         url: https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php
         dest: /opt/tools/

     - name: Recursively change ownership of /opt
       ansible.builtin.file:
         path: /opt/tools
         state: directory
         recurse: yes
         owner: 1000
         group: 1000

     - name: Copy i3 config-file
       ansible.builtin.copy:
         src: ./i3status.conf
         dest: ~/.config/i3/config
         uid: 1000
         gid: 1000
         mode: '0600'
