---
- name: Kali Setup
  hosts: localhost
  become: yes
  tasks:

     - name: Change keyboard layout to de
       ansible.builtin.shell: sudo dpkg-reconfigure keyboard-configuration
       become_user: kali

     - name: Set Hostname
       ansible.builtin.hostname:
          name: "kali"

     - name: Update apt repo and cache
       apt: 
          update_cache: yes
          cache_valid_time: 3600
          upgrade: yes            
            
     - name: Check Ansible-Dependencies
       apt: 
            name: 
                - python2
                - python3
                - python3-pip
                - wget
                - golang-go
                - trufflehog
                - gpg
                - apt-transport-https
                - pipx
                - rustc
                - python2-dev
                - build-essential
                - yara
                - gobuster
                - seclists
                - kali-desktop-i3
                - docker.io
                - docker-compose
                
     - name: Download python2-pip
       ansible.builtin.get_url:
         url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
         dest: /tmp/get-pip.py

     - name: Install python2-pip
       ansible.builtin.shell: python2 /tmp/get-pip.py

     - name: Install Python2 setuptools
       ansible.builtin.shell: python2 -m pip install setuptools

     - name: Install Python2 Dependencies
       ansible.builtin.shell: python2 -m pip install pycrypto distorm3
     
     - name: Install VSCode x86
       ansible.builtin.apt:
         deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
       when: ansible_facts.architecture == "x86_64"

     - name: Install VSCode ARM
       ansible.builtin.apt:
         deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64
       when: ansible_facts.architecture != "x86_64"

     - name: Install impacket
       ansible.builtin.command: 'pipx install git+https://github.com/fortra/impacket'

     - name: Git Pull ponyshell
       git:
         repo: https://github.com/flozz/p0wny-shell
         dest: /opt/tools/p0wny-shell

     - name: Git Pull powercat
       git:
         repo: https://github.com/besimorhino/powercat
         dest: /opt/tools/powercat
         
     - name: Git Pull bloodhound.py
       git:
         repo: https://github.com/dirkjanm/BloodHound.py
         dest: /opt/tools/BloodHound.py

     - name: Git Pull bloodhound.py
       git:
         repo: https://github.com/SpecterOps/BloodHound
         dest: /opt/tools/BloodHound
         
     - name: Git Pull pywhisker
       git:
         repo: https://github.com/ShutdownRepo/pywhisker
         dest: /opt/tools/pywhisker

     - name: Git Pull targetedKerberoast
       git:
         repo: https://github.com/ShutdownRepo/targetedKerberoast
         dest: /opt/tools/targetedKerberoast

     - name: Install ensurepath
       ansible.builtin.command: 'pipx ensurepath'
       
     - name: Install netexec
       ansible.builtin.command: 'pipx install git+https://github.com/Pennyw0rth/NetExec'

     - name: Creates directory
       ansible.builtin.file:
         path: /opt/tools/peas
         state: directory

     - name: Download linpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh
         dest: /opt/tools/peas/

     - name: Download winpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEASany_ofs.exe
         dest: /opt/tools/peas/winpeas.exe

     - name: Download Kerbrute
       ansible.builtin.get_url:
         url: https://github.com/ropnop/kerbrute/releases/latest/download/kerbrute_linux_amd64
         dest: /opt/tools/

     - name: Download volatitilty2
       git:
         repo: https://github.com/volatilityfoundation/volatility
         dest: /opt/tools/volatility

     - name: Download volatitilty3
       git:
         repo: https://github.com/volatilityfoundation/volatility3
         dest: /opt/tools/volatility3

     - name: Download volatility plugins
       git:
         repo: https://github.com/superponible/volatility-plugins
         dest: /opt/tools/volatility-plugins

     - name: Download PKINIT Tools
       git:
         repo: https://github.com/dirkjanm/PKINITtools
         dest: /opt/tools/PKINITtools
         
     - name: Create Resocks-Folder
       ansible.builtin.file:
         path: /opt/tools/resocks
         state: directory

     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Linux_x86_64.tar.gz
         dest: /opt/tools/resocks/
       when: ansible_facts.architecture == "x86_64"

     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/download/v0.1.1/resocks_Linux_arm64.tar.gz
         dest: /opt/tools/resocks/
       when: ansible_facts.architecture != "x86_64"
         
     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Windows_x86_64.zip
         dest: /opt/tools/resocks/

     - name: Create Chainsaw-Folder
       ansible.builtin.file:
         path: /opt/tools/chainsaw
         state: directory

     - name: Download chainsaw
       ansible.builtin.get_url:
         url: https://github.com/WithSecureLabs/chainsaw/releases/latest/download/chainsaw_all_platforms+rules.zip
         dest: /opt/tools/chainsaw/
         
     - name: Download phpreverseshell
       ansible.builtin.get_url:
         url: https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php
         dest: /opt/tools/

     - name: Recursively change ownership of /home/kali/.config/rofi
       ansible.builtin.file:
         path: /opt/tools/bloodhound
         state: directory
         recurse: yes
         owner: 1000
         group: 1000

     - name: Download bloodhound
       ansible.builtin.get_url:
         url: https://raw.githubusercontent.com/SpecterOps/BloodHound/refs/heads/main/examples/docker-compose/docker-compose.yml
         dest: /opt/tools/bloodhound/docker-compose.yml

     - name: Recursively change ownership of /opt
       ansible.builtin.file:
         path: /opt/tools
         state: directory
         recurse: yes
         owner: 1000
         group: 1000

     - name: Recursively change ownership of /home/kali/.config/i3status
       ansible.builtin.file:
         path: /home/kali/.config/i3status
         state: directory
         recurse: yes
         owner: 1000
         group: 1000
         
     - name: Recursively change ownership of /home/kali/.config/i3
       ansible.builtin.file:
         path: /home/kali/.config/i3
         state: directory
         recurse: yes
         owner: 1000
         group: 1000

     - name: Recursively change ownership of /home/kali/.config/rofi
       ansible.builtin.file:
         path: /home/kali/.config/rofi
         state: directory
         recurse: yes
         owner: 1000
         group: 1000
         
     - name: Copy i3status config-file
       ansible.builtin.copy:
         src: ./i3status.conf
         dest: /home/kali/.config/i3status/config
         owner: 1000
         group: 1000
         mode: '0600'
         
     - name: Copy i3 config-file
       ansible.builtin.copy:
         src: ./i3config
         dest: /home/kali/.config/i3/config
         owner: 1000
         group: 1000
         mode: '0600'

     - name: Copy rofi config-file
       ansible.builtin.copy:
         src: ./config.rasi
         dest: /home/kali/.config/rofi/config.rasi
         owner: 1000
         group: 1000
         mode: '0600'
