---
- name: Kali Setup
  hosts: localhost
  become: yes
  tasks:

     - name: Set Hostname
       ansible.builtin.hostname:
          name: "kali"

     - name: Update apt repo and cache
       apt: 
          update_cache: yes
          cache_valid_time: 3600

     - name: Upgrade all apt packages
       apt: 
            name: "*"
            state: latest
            
     - name: Check Ansible-Dependencies
       apt: 
            name: 
                - python3
                - python3-pip
                - wget
                - gpg
                - apt-transport-https
                - pipx
     
     - name: Install Python libraries
       pip: 
            name: 
                - ansible
     
     - name: Check for vscode
       command: apt show code
       register: vscode_present

     - name: Download MS-Keys
       ansible.builtin.shell: 'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg'
       when: vscode_present.rc != 0

     - name: Install MS-Keys
       ansible.builtin.shell: sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
       when: vscode_present.rc != 0

     - name: Install VScode-Repo
       ansible.builtin.shell: sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
       when: vscode_present.rc != 0

     - name: Remove temp files
       ansible.builtin.command: rm -f packages.microsoft.gpg
       when: vscode_present.rc != 0

     - name: Update apt repo and cache
       apt: 
          update_cache: yes
          cache_valid_time: 3600
       when: vscode_present.rc != 0

     - name: Install VS-Code
       apt: 
            name: 
                - code

     - name: Git Pull impacket
       git:
         repo: https://github.com/fortra/impacket
         dest: /opt/tools/impacket

     - name: Git Pull ponyshell
       git:
         repo: https://github.com/flozz/p0wny-shell
         dest: /opt/tools/p0wny-shell

     - name: Git Pull powercat
       git:
         repo: https://github.com/besimorhino/powercat
         dest: /opt/tools/powercat

     - name: Install ensurepath
       ansible.builtin.command: 'pipx ensurepath'
       
     - name: Install netexec
       ansible.builtin.command: 'pipx install git+https://github.com/Pennyw0rth/NetExec'

     - name: Download linpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh
         dest: /opt/tools/peas/

     - name: Download winpeas
       ansible.builtin.get_url:
         url: https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEASany_ofs.exe
         dest: /opt/tools/peas/winpeas.exe

     - name: Download Kerbrute
       ansible.builtin.get_url:
         url: https://github.com/ropnop/kerbrute/releases/latest/download/kerbrute_linux_amd64
         dest: /opt/tools/

     - name: Create Resocks-Folder
       ansible.builtin.file:
         path: /opt/tools/resocks
         state: directory

     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Linux_x86_64.tar.gz
         dest: /opt/tools/resocks/
         
     - name: Download resocks
       ansible.builtin.get_url:
         url: https://github.com/RedTeamPentesting/resocks/releases/latest/download/resocks_Windows_x86_64.zip
         dest: /opt/tools/resocks/
         
     - name: Download phpreverseshell
       ansible.builtin.get_url:
         url: https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php
         dest: /opt/tools/

     - name: Recursively change ownership of /opt
       ansible.builtin.file:
         path: /opt/tools
         state: directory
         recurse: yes
         owner: 1000
         group: 1000
